comment: ""

dataset : # Dataset configuration
  root : "Z:/marvel/marvel-fhnw/data/"                            # root folder of the dataset
  img_channels : 1                                                # grayscale images
  img_size : 200                                                  # original image size
  img_interpolation : 224                                         # size after interpolation or "Null"
  labels_train : data/final/poleno/basic_train.csv                # training labels
  labels_val : data/final/poleno/basic_val_20.csv                 # validation labels
  labels_test : data/final/poleno/basic_test.csv                  # test labels
  filenames : rec_path                                            # column name containing filenames
  img_path : img_path                                             # column name containing absolute or relative image path from root
  particle_id : event_id                                          # how to identify the same particle object

training :
  lr : 0.00005
  batch_size : 8
  num_epochs : 5
  validation_step : 10
  num_nodes : 1
  num_devices : 1
  accumulate_grad_batches : 4

byol:
  backbone : "resnet50"                                 # backbone architecture
  pretrained : False                                    # load backbone pretrained if True
  hidden_layer : "fc"                                   # layer from which to extract embedding features in backbone
  embedding_size : 256                                  # size of the embedding output
  projection_size : 256                                 # size of the projection output
  projection_hidden_size : 4096                         # size of the hidden layer in the projection MLP
  moving_average_decay : 0.99                           # exponential moving average decay for target network
  use_momentum : True                                   # whether to use momentum encoder